### ISSUE TITLE
[QA] search_elastic 2.2.0 has a new admin UI

### ISSUE THREAD

**Issue by jnweiger** [owncloud/docs-server#101]
## WHAT Needs to be Documented?
![image](https://user-images.githubusercontent.com/1108546/154735869-b2f623eb-57d5-4ea6-ab03-e7b4a2f2014e.png)

## WHERE Does This Need To Be Documented (Link)?
https://doc.owncloud.com/server/next/admin_manual/configuration/search/

## WHY Should This Change Be Made?
It differs from 
![image](https://user-images.githubusercontent.com/1108546/154735943-919b2b4a-caf3-463f-aec2-c9a4d8a977b1.png)

## (Optional) What Type Of Content Change Is This? 
- [ ] New Content Addition
- [ ] Old Content Deprecation
- [ ] Existing Content Simplification
- [ ] Bug Fix to Existing Content

## (Optional) Which Manual Does This Relate To?
- [ ] Admin Manual
- [ ] Developer Manual
- [ ] User Manual
- [ ] Android
- [ ] iOS
- [ ] Branded Clients
- [ ] Desktop Client
- [ ] Other

**Comment by jnweiger** [comment]
The dropdown menu has two entries: 'Select Authentication' and 'Username and Password'

When 'Select Authentication' is "selected", username and password are hidden. The Config can also be saved and works fine.
I need to investigate, what the effects the GUI elements actually have. 
I assume 'Select Authentication' is not a setting on its own, it is meant as a title. but I may be wrong.

![image](https://user-images.githubusercontent.com/1108546/154749092-7700d552-ebd0-4b61-a283-da8a1fe52696.png)

----

![image](https://user-images.githubusercontent.com/1108546/154749115-673e3a68-a5dc-4b8f-954d-4894cb08c0a0.png)

**Comment by jnweiger** [comment]
The settings are stored in the database:

```
MariaDB [owncloud]> select * from oc_appconfig where appid = 'search_elastic';
+----------------+----------------------+-----------------+
| appid          | configkey            | configvalue     |
+----------------+----------------------+-----------------+
| search_elastic | enabled              | yes             |
| search_elastic | installed_version    | 2.1.0           |
| search_elastic | scanExternalStorages | 1               |
| search_elastic | servers              | 172.17.0.3:9200 |
| search_elastic | types                | filesystem      |
+----------------+----------------------+-----------------+
5 rows in set (0.002 sec)

**Comment by mmattel** [comment]
> When 'Select Authentication' is "selected"...

Means that you can select between having one and no auth imho. There should be a 'No Authentication' as choice making it clear.

As far I can remember from the code change, wasnt there a 'access key' variant too?

**Comment by hodyroff** [comment]
yes, needs to be possible without authentication as well, please add option @ahherrera

**Comment by ahherrera** [comment]
Hi @hodyroff , when an option is not selected in the select, the connection is without authentication.

**Comment by jnweiger** [comment]
The dropdown menu is confirmed fixed in 2.1.0-rc3
![image](https://user-images.githubusercontent.com/1108546/158892933-ed6a02b5-9220-4847-a508-14ab65e8a906.png)


@mmattel your turn :-)

**Comment by jnweiger** [comment]
> * I see User and Password as option in the screenshot. Mind to make an additional screenshot showing which other items are available resp, how it looks if other items are selected
> 
>     * Are there config.php parameters reflecting the settings available?

![image](https://user-images.githubusercontent.com/1108546/158893194-547d1a18-9092-4a64-b060-8432d13649f5.png)
![image](https://user-images.githubusercontent.com/1108546/158893244-d843db44-d876-4ed4-a3c9-2e08052f5977.png)

There are no settings in config.php, but app config can be manipulated through occ commands:
```
# occ config:list search_elastic
{
    "apps": {
        "search_elastic": {
            "enabled": "yes",
            "group": "content_searchers",
            "installed_version": "2.1.0",
            "nocontent": "false",
            "scanExternalStorages": "1",
            "servers": "elastic:d8035hikt8@172.17.0.3:9200",
            "types": "filesystem"
        }
    }
}

occ config:app:set search_elastic scanExternalStorages --value 0
occ config:app:set search_elastic scanExternalStorages --value 1
...
```

**Comment by mmattel** [comment]
Great. Any info about the implementation using an API key? This was a requirement imho.

**Comment by jnweiger** [comment]
> Great. Any info about the implementation using an API key? This was a requirement imho.

not implemented for 2.1.0

**Comment by jnweiger** [comment]
## Update for 2.1.1
(changed the title of this issue to reflect 2.1.1)

* Password and user are now stored in separate fields. The password is stored encrypted.
```
{
    "apps": {
        "search_elastic": {
            "enabled": "yes",
            "installed_version": "2.1.0",
            "nocontent": "false",
            "scanExternalStorages": "1",
            "server_password": "v2|c3c70f0159fea863abb7fc981700e19a|e5196819bb324942d6b1b7d193508f12|bd6bc80881e71f6ed6f3503d46a83973859431416be092a8ad12bb6cdb7f60d4f680f116b877e84abfe5e9d2109179f0925d0607b4bccefd3877fff08311593b",
            "server_user": "elastic",
            "servers": "172.17.0.3:9200",
            "types": "filesystem"
        }
    }
}
```

**Comment by jnweiger** [comment]
## Update for 2.2.0
(changed the title of this issue to reflect 2.2.0)

* username is now stored in a different field in oc_appconfig
* Password is now stored in the oc_credentials table (encryption handled by the CredentialsManager)
* A proper URL with HTTP:// or HTTPS:// can be specfied.
* the dropdown menu has now 3 different settings:

![image](https://user-images.githubusercontent.com/1108546/176073706-fb5e737a-71e1-4f01-a93c-717d65bd13b3.png)

----

![image](https://user-images.githubusercontent.com/1108546/176073905-dcae6336-75c9-46a8-99e5-c41acbe3f00f.png)

----

![image](https://user-images.githubusercontent.com/1108546/176074025-519242ff-7d78-4ab0-9117-4748247e0639.png)

----

![image](https://user-images.githubusercontent.com/1108546/176074168-f7e265e4-fe6f-473f-bb43-56f011739fd4.png)

**Comment by mmattel** [comment]
@jnweiger thanks for the screenshots, will proceed asap

**Comment by jvillafanez** [comment]
To prevent confusion, the API key needed for ownCloud is the encoded version. From https://www.elastic.co/guide/en/elasticsearch/reference/current/security-api-create-api-key.html
```
{
  "id": "VuaCfGcBCdbkQm-e5aOx",        
  "name": "my-api-key",
  "expiration": 1544068612110,         
  "api_key": "ui2lp2axTNmsyakw9tvNnw", 
  "encoded": "VnVhQ2ZHY0JDZGJrUW0tZTVhT3g6dWkybHAyYXhUTm1zeWFrdzl0dk5udw=="  
}
```
The admin will need to supply the encoded one (`VnVhQ2ZHY0JDZGJrUW0tZTVhT3g6dWkybHAyYXhUTm1zeWFrdzl0dk5udw==` not `ui2lp2axTNmsyakw9tvNnw`)

**Comment by jnweiger** [comment]
> @jnweiger thanks for the screenshots, will proceed asap

@mmattel Thanks to @jvillafanez ' comment, I've changed the hint shown in the empty API Key entry field to say `Encoded API Key` and updated the screenshot above.

**Comment by mmattel** [comment]
Great, thanks a lot for the effort!

**Comment by jnweiger** [comment]
There is a section about a "Full Text Search App" https://github.com/owncloud/docs-webui/blob/master/modules/classic_ui/pages/files/webgui/search.adoc#full-text-search-app
* It is unclear, which app actually is the "Full Text Search App" descibed there. A link or an exact name should be given.
* Wildcards * and ? are explained, but logic AND, OR, NOT operators are not mentioned.

I suggest to add some of the details found in https://github.com/owncloud/search_elastic/issues/286 to that section.
