### ISSUE TITLE
Installation guide: Database: Grant privileges + create user no longer works on mysql

### ISSUE THREAD

**Issue by voroyam** [owncloud/docs-server#1061]
## WHAT Needs to be Documented?
This no longer works / Never worked on mysql dbs, maria dbs are fine:

```
GRANT ALL PRIVILEGES ON owncloud.* \
  TO owncloud@localhost \
  IDENTIFIED BY '${sec_db_pwd}'";
```

We need a **note** that this does not work on mysql db and that the commands below needs to be used, maybe a link here: 

https://doc.owncloud.com/server/next/admin_manual/installation/manual_installation/manual_installation_db.html#notes-for-mariadb-higher-than-10-4-3

## WHERE Does This Need To Be Documented (Link)?
https://doc.owncloud.com/server/next/admin_manual/installation/quick_guides/ubuntu_20_04.html#configure-the-database

https://doc.owncloud.com/server/next/admin_manual/installation/quick_guides/ubuntu_22_04.html#configure-the-database

## WHY Should This Change Be Made?
because it will throw an error:

```
ERROR 1064 (42000): You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'IDENTIFIED BY 'password'' at line 3
```

This works, as it's also stated in the detailed guide:

```
 CREATE USER IF NOT EXISTS 'dbadmin'@'localhost' IDENTIFIED BY 'password';
 GRANT ALL PRIVILEGES ON *.* TO 'dbadmin'@'localhost' WITH GRANT OPTION;
 FLUSH PRIVILEGES;
 SHOW GRANTS FOR 'dbadmin'@'localhost';
```

**Comment by voroyam** [comment]
@tkinsky

**Comment by mmattel** [comment]
> This works, as it's also stated in the detailed guide

@voroyam 
means that command would work on both mariadb/mysql databased?
and in case yes, we could use it in the erroring page...

**Comment by ockinsky** [comment]
See MySQL manual 'What's new in Mysql 8':

'''
The following features related to account management are removed:

Using [GRANT](https://dev.mysql.com/doc/refman/8.0/en/grant.html) to create users. Instead, use [CREATE USER](https://dev.mysql.com/doc/refman/8.0/en/create-user.html). Following this practice makes the NO_AUTO_CREATE_USER SQL mode immaterial for [GRANT](https://dev.mysql.com/doc/refman/8.0/en/grant.html) statements, so it too is removed, and an error now is written to the server log when the presence of this value for the sql_mode option in the options file prevents [mysqld](https://dev.mysql.com/doc/refman/8.0/en/mysqld.html) from starting.
'''
source: https://dev.mysql.com/doc/refman/8.0/en/mysql-nutshell.html

The auth option is not present anymore in the manual for the grant command, too (has been present in earlier versions):
https://dev.mysql.com/doc/refman/8.0/en/grant.html

the 'right' way is to have the user creation separated, including the password declaration, 
then create the grant. This works for mariadb, too. 
Anyway, it was depending from a sql mode variable before and still is with mariadb.

**Comment by voroyam** [comment]
> > This works, as it's also stated in the detailed guide
> 
> @voroyam means that command would work on both mariadb/mysql databases? and in case yes, we could use it in the erroring page...

yes, that would be easier.
