### ISSUE TITLE
Loop in the next -> next -> next ... chain

### ISSUE THREAD

**Issue by jnweiger** [owncloud/docs-server#1138]
* Browse https://doc.owncloud.com/server/10.13/admin_manual/installation/
* Check the left sidebar, open the folding triangles, so that all entries under the 'Installation' heading are visible
![grafik](https://github.com/owncloud/docs-server/assets/1108546/0337eb43-6742-4419-b6e1-43185a093f70)
----
* The next visible entry below 'Configuration Notes and Tips' is 'Installation Options'.
* Note that this entry has the same URL as the `Installation` page, that we started with. BAD
* This has the effect, that following the `Next` links at the bottom of `Configuration Notes and Tips` loops back to `Installation`. BAD
* The Heading and text in https://doc.owncloud.com/server/10.13/admin_manual/installation actually discusses Installation Options. 

Expected behaviour:
* The chain of `Next` links is linear.
   * It should neither loop back
   * nor skip any pages.
* https://doc.owncloud.com/server/10.13/admin_manual/installation should be a short general introduction (e.g. mention our built in dependency checker, to convey some confidence in the process), and not discuss Installation Options.

**Comment by mmattel** [comment]
There is a fix, see referenced PR.

**BUT**: dont try to intend to fix with such things the currently missing pdf creation. This will come with Antora 3 which provides a clean nav access...
