### ISSUE TITLE
pdf viewer - new system config parameter

### ISSUE THREAD

**Issue by DeepDiver1975** [owncloud/docs-server#1247]
@mmattel new config parameter for documentation.... THX

https://github.com/owncloud/files_pdfviewer/pull/331/files#diff-a1dedb2c63ef1dc17c3add0c4bff4691baf93165f3a9d3150374efbc88d85a37R7

_Originally posted by @DeepDiver1975 in https://github.com/owncloud/files_pdfviewer/issues/333#issuecomment-1891890977_

**Comment by mmattel** [comment]
@DeepDiver1975 
I need to add a new `config.apps.sample` entry in core for Files PDF Viewer. When merged, I can do a `config-to-docs` run to transport the change into thsi docs. Therefore I would need the following infos:
* a description text
* which values are possible like true/false, yes/no, ...

We can also have a short call to clarify if this is easier.

**Comment by DeepDiver1975** [comment]
> * which values are possible like true/false, yes/no, ...

`yes` to enable scripting 
anything else is seen as disable scripting

**Comment by DeepDiver1975** [comment]
> * a description text

It is bad - don't use it :rofl:

**Comment by mmattel** [comment]
Closing via #1219
