### ISSUE TITLE
New feature: PDF file classification

### ISSUE THREAD

**Issue by jnweiger** [owncloud/docs-server#1248]
## WHAT Needs to be Documented?
XPath syntax for various document types are tricky. 
We need to show good examples for office documents (old) and PDF files (new).
Also we should show the usage of exiftool to retrieve the exact strings used in the XPath.
XPath functions like `local-name()` and `starts-with()` should be documented as working, `ends-with()` as not working.

See
- https://github.com/owncloud/enterprise/issues/5648#issuecomment-1905105773
- https://github.com/owncloud/files_classifier/pull/866
- https://github.com/owncloud/files_classifier/issues/857#issuecomment-1903719389

## WHERE Does This Need To Be Documented (Link)?
https://doc.owncloud.com/server/10.13/admin_manual/enterprise/document_classification/classification_and_policy_enforcement.html#automated-classification-based-on-document-metadata

## WHY Should This Change Be Made?

The UI is non-intuitive. 
Admins need to understand the different XPath queries needed for different file types.

## (Optional) What Type Of Content Change Is This? 
- [ ] New Content Addition
- [ ] Old Content Deprecation
- [ ] Existing Content Simplification
- [ ] Bug Fix to Existing Content

## (Optional) Which Manual Does This Relate To?
- [ ] Admin Manual
- [ ] Developer Manual
- [ ] User Manual
- [ ] Android
- [ ] iOS
- [ ] Branded Clients
- [ ] Desktop Client
- [ ] Other

**Comment by mmattel** [comment]
Should we combine the content with the upcoming https://github.com/owncloud/files_classifier/pull/796 PR?

**Comment by jnweiger** [comment]
> Should we combine the content with the upcoming [owncloud/files_classifier#796](https://github.com/owncloud/files_classifier/pull/796) PR?

Yes, same thing.
