### ISSUE TITLE
New branch for server 10.14

### ISSUE THREAD

**Issue by jnweiger** [owncloud/docs-server#1272]
We are about to release server core 10.14.0 final. Before tagging (and building) the final release, we should prepare the 10.14 documentation branch.

@dragotin agreed with that plan.

I started looking myself into https://github.com/owncloud/docs/blob/master/docs/build-the-docs.md
But I'd prefer that you prepare the branch please.

**Comment by dragotin** [comment]
@mmattel please help here - thanks!

**Comment by mmattel** [comment]
Closed via #1276
