### ISSUE TITLE
[QA] Prepare for 10.15.0 release

### ISSUE THREAD

**Issue by jnweiger** [owncloud/docs-server#1315]
## WHAT Needs to be Documented?
We want to be prepared for the release of server core 10.15.0 
This needs a new doc branch according to https://github.com/owncloud/docs-server/blob/master/docs/new-version-branch.md

## WHERE Does This Need To Be Documented (Link)?

Server Release Ticket: https://github.com/owncloud/enterprise/issues/6528

## (Optional) What Type Of Content Change Is This? 
- [ ] New Content Addition
- [ ] Old Content Deprecation
- [ ] Existing Content Simplification
- [ ] Bug Fix to Existing Content

## (Optional) Which Manual Does This Relate To?
- [ ] Admin Manual
- [ ] Developer Manual
- [ ] User Manual
- [ ] Android
- [ ] iOS
- [ ] Branded Clients
- [ ] Desktop Client
- [ ] Other

**Comment by DeepDiver1975** [comment]
10.15 is release long ago -> close
