### ISSUE TITLE
Improvements to kiteworks migration guide

### ISSUE THREAD

**Issue by DeepDiver1975** [owncloud/docs-server#1319]
refs https://doc.owncloud.com/server/10.14/admin_manual/maintenance/migrating_to_kiteworks.html

It is expected that the guide is fully self-contained and users do not need to read any other documentation parts 

# Improvements
- [ ] explain how to install owncloud app and rclone
- [ ] explain how to run the migration in a docker environment
- [ ] explain to enable the migrate_to_kiteworks app and how
- [ ]

**Comment by jnweiger** [comment]
Migration with docker
=====================

You receive a passwor protected download link for the migration tool, that looks similar to this:

  https://cloud.owncloud.com/s/XXXXXXXXX

Log in with a web browser and hit the Download button in top right corner.
 -> a file 'kiteworks migrate.zip' is downloaded, ca 160 MB.
Transfer this file into the owncloud server that is to be migrated.
As root shell access to the server is needed anyway, scp can be used.
Let's assume the server is reachable as ocXXX.owncloud.works
All commands you need to enter are shown with a leading '$ ' here. This 
symbolizes the shell prompt. Your prompt most certainly looks different.
We copy the download into the server and enter the server via ssh:

$ OC_NAME=ocXXX.owncloud.works
$ scp $HOME/Downloads/kiteworks\ migration.zip  root@$OC_NAME:/tmp
$ ssh root@$OC_NAME

When logged into the owncloud server host:
$ cd /tmp
$ unzip kiteworks\ migration.zip
$ cd kiteworks\ migration
$ unzip kiteworks_rclone.zip

Now find the docker container id of the running owncloud instance. In this example
the container id is ea6df2e097c9

$ docker ps
  CONTAINER ID   IMAGE                     COMMAND                  CREATED       STATUS       PORTS                                       NAMES
 ea6df2e097c9   owncloud/server:10.14.0   "/usr/bin/entrypoint…"   2 hours ago   Up 2 hours   0.0.0.0:8080->8080/tcp, :::8080->8080/tcp   oc-10140-20240618
$ DOCKERID=ea6df2e097c9

Now copy rclone and the app into the container and enter the container.

$ docker cp rclone_linux_amd64  $DOCKERID:/tmp
$ docker cp migrate_to_kiteworks.tar.gz  $DOCKERID:/tmp
$ docker exec -ti $DOCKERID /bin/bash

When logged into the docker container:

$ install /tmp/rclone_linux_amd64 /usr/local/bin/rclone
$ occ market:install --local /tmp/migrate_to_kiteworks.tar.gz
$ occ app:enable migrate_to_kiteworks
$ occ migrate:to-kiteworks --help

  Description:
    Bye bye ownCloud ...

  Usage:
    migrate:to-kiteworks [options] [--] <kiteworks-admin>

In case 'occ app:enable' fails with '... rclone could not be found' you can
use a more complex command that also specifies the directory, where rclone is installed through the PATH variable:

$  su www-data -c "PATH=/usr/local/bin /usr/bin/php /var/www/owncloud/occ app:enable migrate_to_kiteworks"

Note that everything after -c must be enclosed in doublequotes (") as shown above.

**Comment by DeepDiver1975** [comment]
guest users will be mapped to kitewors user profile 'restricted' by default.
this profile does not allow files to be shared with as collaborator.

either the existing profile is changed or a new profile is created. the migrate command allows to specify an alternative profile

admin ui: 
![image](https://github.com/user-attachments/assets/566d3cb3-54d5-4163-998a-1d49a141b7b1)

**Comment by DeepDiver1975** [comment]
migrate command is spilt into 3 commands: user, files, shares ...

```shell
 migrate
  migrate:to-kiteworks:files             Migrates ownCloud files and folders to the configured Kiteworks instance. See also: https://doc.owncloud.com/server/latest/admin_manual/maintenance/migrating_to_kiteworks.html
  migrate:to-kiteworks:init              Initialize the migration process. See also: https://doc.owncloud.com/server/latest/admin_manual/maintenance/migrating_to_kiteworks.html
  migrate:to-kiteworks:shares            Migrates ownCloud shares to the configured Kiteworks instance. See also: https://doc.owncloud.com/server/latest/admin_manual/maintenance/migrating_to_kiteworks.html
  migrate:to-kiteworks:users             Migrates ownCloud users to the configured Kiteworks instance. See also: https://doc.owncloud.com/server/latest/admin_manual/maintenance/migrating_to_kiteworks.html
  migrate:to-kiteworks:verify            Verifies the ownCloud instance to be ready for migration. See also: https://doc.owncloud.com/server/latest/admin_manual/maintenance/migrating_to_kiteworks.html

**Comment by DeepDiver1975** [comment]
Unsupported scenario:
- Folder F is shared with User A
- Folder F/X/YZ is share with User A

Kiteworks does not allow this - this can lead to unexpected folder structure for the user in kiteworks as well as missing access permissions.

**Comment by mmattel** [comment]
Changes:

* [ ] Guestusers can be migrated
* [ ] Disabled users:
To be defined, most likely be added
* [ ] Migrate Files:
No rerun migrating files when migrate shares has been started.
(Info: may conflict with root folder name `owncloud`)
* [ ] Shares in the same hierarchy with same permissions are not created
Shares with higher permissions are created
* [ ] Migarte command sort order:
`init`, `verify`, `users`, `files`, (! cut !), `shares`
