### ISSUE TITLE
[QA] configreport new feature needs documentation: telemetry

### ISSUE THREAD

**Issue by jnweiger** [owncloud/docs-server#1347]
## WHAT Needs to be Documented?
https://github.com/owncloud/configreport/pull/197
occ configreport:send-telemetry

* config->getSystemValue('telemetry.enabled', true);
* if ($licenseKey === "") {            return false;
* $telemetryUrl = 'https://telemetry.owncloud.com/oc10-telemetry';
* logger->info("Telemetry data submitted to $telemetryUrl with request id: $requestId");
* $id = Uuid::uuid4()->toString(); config->setAppValue("configreport", "telemetry.id", $id);
* getAppValue("configreport", "telemetry.nextSubmission",
* DateInterval::createFromDateString('1 day')

* ??? email cc of telemetry report... ???

## WHERE Does This Need To Be Documented (Link)?
https://doc.owncloud.com/server/next/admin_manual/troubleshooting/providing_logs_and_config_files.html

## (Optional) What Type Of Content Change Is This? 
- [ ] New Content Addition
- [ ] Old Content Deprecation
- [ ] Existing Content Simplification
- [ ] Bug Fix to Existing Content

## (Optional) Which Manual Does This Relate To?
- [ ] Admin Manual
- [ ] Developer Manual
- [ ] User Manual
- [ ] Android
- [ ] iOS
- [ ] Branded Clients
- [ ] Desktop Client
- [ ] Other

**Comment by mmattel** [comment]
@jnweiger
This MUST go first into the config.sample in the server repo and I can do a config to docs run!!
Ping me in the chat system.

**Comment by jnweiger** [comment]
https://github.com/owncloud/core/pull/41283

**Comment by jnweiger** [comment]
Followup -> #1350
