### ISSUE TITLE
Update pgsql system requirements

### ISSUE THREAD

**Issue by phil-davis** [owncloud/docs-server#186]
## WHAT Needs to be Documented?
In issue https://github.com/owncloud/enterprise/issues/5064 we are doing testing to confirm that later pgsql major versions work OK with oC10. After that testing is complete, we need to update the system requirements matrix to include whatever pgsql versions are confirmed to work.

## (Optional) What Type Of Content Change Is This? 
- [ ] New Content Addition
- [ ] Old Content Deprecation
- [ ] Existing Content Simplification
- [ ] Bug Fix to Existing Content

## (Optional) Which Manual Does This Relate To?
- [ ] Admin Manual
- [ ] Developer Manual
- [ ] User Manual
- [ ] Android
- [ ] iOS
- [ ] Branded Clients
- [ ] Desktop Client
- [ ] Other

**Comment by mmattel** [comment]
Closing via #206 (Add support for pgsql 11 12 13 14)
