### ISSUE TITLE
Database backup command misses transaction parameter

### ISSUE THREAD

**Issue by d7oc** [owncloud/docs-server#256]
## WHAT Needs to be Documented?
The backup section at https://doc.owncloud.com/server/next/admin_manual/installation/docker/#upgrading-owncloud-on-docker describes a backup using
```
/usr/bin/mysqldump -u root --password=owncloud \
     owncloud > owncloud_$(date +%Y%m%d).sql
```
This command missed the transaction parameter `--single-transaction` which instructs `mysqldump` to execute the backup job in a single transaction on the database layer so that no other operation in between can lead to an inconsistent backup state. See https://dev.mysql.com/doc/refman/8.0/en/mysqldump.html#option_mysqldump_single-transaction
If there is binary data in the database it would also be recommended to add `--hex-blob` see https://dev.mysql.com/doc/refman/8.0/en/mysqldump.html#option_mysqldump_hex-blob

## WHERE Does This Need To Be Documented (Link)?
In my opinion at least `--single-transaction` should be added

## WHY Should This Change Be Made?
Without the parameter the mysqldump might be in an inconsistent state if another service still adds data.

## (Optional) What Type Of Content Change Is This? 
- [ ] New Content Addition
- [ ] Old Content Deprecation
- [ ] Existing Content Simplification
- [X] Bug Fix to Existing Content

## (Optional) Which Manual Does This Relate To?
- [X] Admin Manual
- [ ] Developer Manual
- [ ] User Manual
- [ ] Android
- [ ] iOS
- [ ] Branded Clients
- [ ] Desktop Client
- [ ] Other

**Comment by mmattel** [comment]
@d7oc thanks for highlighting this 👍 will file a PR asap.
