### ISSUE TITLE
background_jobs_configuration.adoc correction

### ISSUE THREAD

**Issue by ervee** [owncloud/docs-server#273]
## WHAT Needs to be Documented?
[Background Jobs Configuration](https://doc.owncloud.com/server/10.10/admin_manual/configuration/server/background_jobs_configuration.html)

## WHERE Does This Need To Be Documented (Link)?
n/a

## WHY Should This Change Be Made?
Seems like an error

## (Optional) What Type Of Content Change Is This? 
- [ ] New Content Addition
- [ ] Old Content Deprecation
- [ ] Existing Content Simplification
- [X] Bug Fix to Existing Content

## (Optional) Which Manual Does This Relate To?
- [X] Admin Manual
- [ ] Developer Manual
- [ ] User Manual
- [ ] Android
- [ ] iOS
- [ ] Branded Clients
- [ ] Desktop Client
- [ ] Other

In background_jobs_configuration.adoc there is this line:
```For example, to run a Cron job on a *nix system every 15 minutes (recommended), under the default web server user (often, www-data or wwwrun) you must set up the following Cron job to call the occ background:cron command:```

I think that should not be ```background:cron``` but ```system:cron``` as in the example below the line. The ```background:cron``` command is to set the configuration to cron mode and is explained in the beginning of the page.

**Comment by mmattel** [comment]
@ervee thanks for bringing this to our attention 👍 

@jnweiger mind to have a look on that to clarify what is correct?
