### ISSUE TITLE
[QA] User manual is not listed in https://doc.owncloud.com/server/latest

### ISSUE THREAD

**Issue by jnweiger** [owncloud/docs-server#274]
http://doc.owncloud.com/server/latest only lists 
* Admin Manual
* Developer Manual

Expected behaviour:
* User Manual

should also be there.

The redirect https://doc.owncloud.com/server/latest/user_manual brings me to https://doc.owncloud.com/webui/next/classic_ui/
This is a hint, that the classic User Manual no longer exists?

I am worried, that a user who wants to learn about concept topics like e.g. apps ecosystem or sharing would not expect that info under: User Interfaces -> Web

**Comment by mmattel** [comment]
The server user manual has been relocated which was part of the necessary streamlining process for the current and upcoming products.

**Soon:**
* oCIS will be part of the Server tab
* ownCloud Web will be part of the Web tab

![image](https://user-images.githubusercontent.com/3321281/165233781-28c6bc55-4981-41da-9fe0-db2a9a523948.png)

Closing
