### ISSUE TITLE
Improvements on the session handling

### ISSUE THREAD

**Issue by jvillafanez** [owncloud/docs-server#283]
## WHAT Needs to be Documented?
New config options added in https://github.com/owncloud/core/pull/39916 . Some old options might need an update for clarification

## (Optional) What Type Of Content Change Is This? 
- [x] New Content Addition
- [ ] Old Content Deprecation
- [ ] Existing Content Simplification
- [ ] Bug Fix to Existing Content

## (Optional) Which Manual Does This Relate To?
- [x] Admin Manual
- [ ] Developer Manual
- [ ] User Manual
- [ ] Android
- [ ] iOS
- [ ] Branded Clients
- [ ] Desktop Client
- [ ] Other

Hopefully, https://github.com/owncloud/core/pull/39916#issuecomment-1109541854 and the information in the config.sample.php file is enough, if not please ask.

This is expected to be in 10.9.2

**Comment by mmattel** [comment]
Fixed via https://github.com/owncloud/docs-server/pull/301 (Config To Docs run)
