### ISSUE TITLE
Wrong owner of "apps" folder after doing manual upgrade

### ISSUE THREAD

**Issue by ChrisTG742** [owncloud/docs-server#285]
## WHAT Needs to be Documented?
Following the manual update steps on "Manual ownCloud Upgrade" lead to a non-writeable "apps" folder

## WHERE Does This Need To Be Documented (Link)?
https://doc.owncloud.com/server/next/admin_manual/maintenance/upgrading/manual_upgrade.html 

## WHY Should This Change Be Made?
Because updating apps is not possible any more after upgrading.

## (Optional) What Type Of Content Change Is This? 
- [ ] New Content Addition
- [ ] Old Content Deprecation
- [ ] Existing Content Simplification
- [X ] Bug Fix to Existing Content

## (Optional) Which Manual Does This Relate To?
- [X ] Admin Manual
- [ ] Developer Manual
- [ ] User Manual
- [ ] Android
- [ ] iOS
- [ ] Branded Clients
- [ ] Desktop Client
- [ ] Other

Fix: Change the lines

Set the ownership for all files and folders to www-data:www-data for the config and data directory. Note that it is not mandatory to set the ownership of the data/ directory as it should already have the correct ownership and it can take a while to finish, depending on the size:

sudo chown -R www-data:www-data /var/www/owncloud/config
sudo chown -R www-data:www-data /var/www/owncloud/data

to

Set the ownership for all files and folders to www-data:www-data for the config and data directory. Note that it is not mandatory to set the ownership of the data/ directory as it should already have the correct ownership and it can take a while to finish, depending on the size:

sudo chown -R www-data:www-data /var/www/owncloud/config
sudo chown -R www-data:www-data /var/www/owncloud/data
sudo chown -R www-data:www-data /var/www/owncloud/apps

**Comment by mmattel** [comment]
@ChrisTG742 thanks for raising the issue, fix is on the way.

**Comment by ChrisTG742** [comment]
Oh, just a small missing: The text should be supplemented by "apps", too, I think:

"Set the ownership for all files and folders to www-data:www-data for the config, data and apps directories. Note that it is not mandatory to set the ownership of the data/ directory as it should already have the correct ownership and it can take a while to finish, depending on the size:"

**Comment by mmattel** [comment]
@ChrisTG742 mind to file a PR with your suggestions?
Regrading ownership and the data directory, yes this is true and an admin knows if this is necessary or not. We have seen that sometimes admins do things that are not always streamlined causing starange behaviour. At this step things get "cleand" again 😅 Therefore we think it is better to keep it, at least with the manual upgrade. If you use the script guided process, you get asked.
