### ISSUE TITLE
Instructions for creating a new doc branch is unclear

### ISSUE THREAD

**Issue by jnweiger** [owncloud/docs-server#308]
Step1, Item 8 at https://github.com/owncloud/docs-server/blob/master/docs/new-version-branch.md?plain=1#L16
mentions modules/ROOT/pages/server_releases.adoc
which is not in this repo. (There is one in docs, but that one ends at 10.7 )

I've skipped this item for creating  https://github.com/owncloud/docs-server/tree/10.10 --
`yarn antora` neverthless ran fine here.

I'd guess, I now need to do two PRs, one for docs-server, and one for docs and sort the items into the two repos as they fit best. I am stopping before step 2 to avoid more chaos.

**Comment by jnweiger** [comment]
Instructions are updated:
* in docs-server https://github.com/owncloud/docs-server/commit/9d11d50a7ae8bf617b0fc5aeac28935784548358
* in docs https://github.com/owncloud/docs/commit/d4cdd033def35d6ffa6636ff2df1595e1a85e3ba

**Comment by mmattel** [comment]
Closing via #310
