### ISSUE TITLE
Redis on Ubuntu 22.04 + PHP 7.4

### ISSUE THREAD

**Issue by pako81** [owncloud/docs-server#367]
Related to https://github.com/owncloud/docs-server/pull/366

In https://doc.owncloud.com/server/10.10/admin_manual/configuration/server/caching_configuration.html we document:

> The default shipped Redis version and the php-redis extension for Ubuntu 20.04 is 5.x. With Redis version 6, a new authentication mechanism has been introduced named ACL (Access Control Lists). ownCloud does not currently support Redis ACL´s, but does support the password protection available with current Redis versions.

However, the default shipped Redis version for Ubuntu 22.04 is 6.0.16 while the php7.4-redis extension from ondrej/php PPA is 5.3.7 --> we need to be sure that this combination does not cause any issues.

In my test environment, Redis seems to work correctly and no warning are displayed in the General Section of the Admin Page once Redis has been configured for Transactional File Locking.

@mmattel @phil-davis @jnweiger

**Comment by mmattel** [comment]
**In a nutshell:**
Check if the redis php extension version 5.3.x works with redis server 6.x

Imho yes, because:
* backwards compatibility
* would break existing installations where you have a distributed or clustered redis setup

**Comment by mmattel** [comment]
Here is the official answer:
![image](https://user-images.githubusercontent.com/3321281/173346688-5a36ff6e-202a-4c86-aa04-08e1a760e171.png)
Closing
