### ISSUE TITLE
[QA] updatenotification of server 10.7.0 fails to point to 10.8.0 changelog

### ISSUE THREAD

**Issue by jnweiger** [owncloud/docs-server#39]
Seen in 10.7.0 

The updater section in the web UI refers to the Changelog with the *i* icon. https://owncloud.org/changelog/#latest10.8

![image](https://user-images.githubusercontent.com/1108546/152800609-2a53d985-fd34-41da-883e-8479e203ba97.png)

We no longer serve this URL, although 10.7.x and 10.8.x servers are still out there.
the new URL is https://owncloud.com/changelog/server/#10.8.0
In 10.9.1 we use correctly use this schema. But we cannot update old servers before they update.

I suggest to add a redirect to forward the old URL to the new URL.

**Comment by mmattel** [comment]
Closing, there is no owncloud.org anymore
