### ISSUE TITLE
update script owncloud_prep.sh mentioned in the documentation deletes data directory during an upgrade

### ISSUE THREAD

**Issue by johnxba** [owncloud/docs-server#448]
## WHAT Needs to be Documented?
The update script owncloud_prep.sh mentioned in the documentation does not work as expected.

## WHERE Does This Need To Be Documented (Link)?
https://doc.owncloud.com/server/next/admin_manual/installation/manual_installation/script_guided_install.html#creating-the-scripts

## WHY Should This Change Be Made?
While performing an upgrade it deletes data directories. This obviously causes data loss. An upgrade should not delete existing data.

## (Optional) What Type Of Content Change Is This? 
- [X] Bug Fix to Existing Content

Please correct the script to handle upgrades properly.

## (Optional) Which Manual Does This Relate To?
- [X] Admin Manual

Owncloud was not updating from version 10.9 tot 10.10 using the web interface or the command line interface occ. An attempt was made to update manually using the scripts mentioned in the documentation. 

The tar.bz2 file was downloaded from here: https://download.owncloud.com/server/stable/owncloud-latest.tar.bz2

```
sudo -uwww-data ./occ maintenance:mode --on
```
```
./instance.sh
Do you want to secure your .htaccess files post installing/upgrade (y/N)? N
Do you want to install a new instance (y/N)? N
Do you want to upgrade an existing installation (y/N)? Y
Use links for data and apps-external directories (Y/n)? N
Do you want to chmod/chown these links (y/N)? N
Please specify the tar file to extract with full path: /home/user/2022/owncloud-latest.tar.bz2
```
```
sudo -u www-data ./occ upgrade
```
The data directory has to be restored manually.
```
sudo -uwww-data ./occ maintenance:mode --off
```

The upgrade seemed to work, but it is unclear if something is broken as a result of this bug.

**Comment by mmattel** [comment]
@johnxba the script never touches the apps-external and data directory, independent of the method used.

You will get asked - as you have shown in your comment, if you are using links or normal directories.

. In case of links, the apps-external and data directories get relinked.
. In case of normal directories as you use it, you get a note at the end to copy/move those directories to the new location. The script does not do this for you for security reasons. As a data directory can be huge, there are multiple ways to relocate it. As admin, you know what is best in your environment to do so.

The messages printed on success on how to finalize your installation/upgrade are important to be done, you may just have missed that particular item.

As a suggestion for the next upgrade, take care on the success messages printed at the end. Consider moving the data and apps-external directory to a location outside of the owncloud directory and relink it to the original location. Adopt the setting in the instance script and use links in the questionaire. Relinking will be done by the script automatically which eases the upgrade task a lot. Note that you can test the procedure easily by just copying the owncloud directory and do all the steps as you would do in a productive instance. This will give you confidence about the steps before you touch the live system.

Let us know if you have more questions.

I will close that issue as there is no defect in the script.

**Comment by johnxba** [comment]
@[mmattel](https://github.com/mmattel) Thanks for your response.

I am looking at this from a user perspective. Deletion of the data directory is not what I expect to happen. I do not expect to spend time figuring out what the upgrade script does.

> the script never touches the apps-external and data directory, independent of the method used.

The data directory in the location being upgraded was factually deleted without warning.  This is an observation. I'm not looking at the script to predict that.
```
SUCCESS

Please manually run: cd /var/www/owncloud
Please manually run: sudo -uwww-data ./occ upgrade
Copy any changes manually added in .user.ini and .htaccess from the backup
Please manually run: sudo -uwww-data ./occ maintenance:mode --off
Please manually remove the directory of the old instance: /var/www/owncloud_2022-06-20-00.00.00
When successfully done, re-run this script to secure your .htaccess files

Please move/copy your data and apps-external directory manually back to the original location BEFORE running the upgrade command !
```
The documentation nor the script does not explain clearly what the script does. It should explicitly warn that the `data` directory content will be removed. Better: make sure that data is not deleted at all. Or: if it is moved, to ask for permission to return it to make the site functional again.

>In case of normal directories as you use it, you get a note at the end to copy/move those directories to the new location. The script does not do this for you for security reasons.

Indeed, I use normal directories. What "new location" are you referring to? I see no need to move the data to location different to where it was (`/var/www/owncloud/data`). If you meant to say to put the data back where it was, that should be extensively described.

Also, what are these "security reasons"? Please elaborate on this as I have an interest in security.

> Consider moving the data and apps-external directory to a location outside of the owncloud directory and relink it to the original location.

Why would I want to do that? `data` was already present, this an upgrade to an installation that does not use any links.

The existing install `/var/www/owncloud` contains all owncloud directories and files. `/var/www/owncloud/data` contains data.

> Adopt the setting in the instance script and use links in the questionaire.

A similar note is is in the documentation. Is the use of the word "adopt" intended? I am guessing the intended word is "adapt".

adapt: change the settings to fit the circumstances
adopt: use a predefined set of settings

There were no changes necessary in script `instance.sh`.

>  Note that you can test the procedure easily by just copying the owncloud directory and do all the steps as you would do in a productive instance. This will give you confidence about the steps before you touch the live system.

That's a good idea, that should be in the manual. Probably with a warning relating to changes to the database.

> I will close that issue as there is no defect in the script.

In my opinion both the script and the documentation should be updated, preferably per the comments, requests, recommendations and advice in this message.

This is part of the output:
>Please move/copy your data and apps-external directory manually back to the original location BEFORE running the upgrade command !

This does not explain what has happened or what will happen (read: what the script did). Secondly, this warning follows the advice to run the occ upgrade. Thirdly, this text comes after the text advises to delete the backup which contains the `data` directory.

At that point the data directory would be deleted. The user didn't move anything, please make sure to use proper wording in the explanation in both the documentation and the script and use the text in the correct context and order.

Still not looking at the script, I suspect/imagine that the owncloud directory is renamed/moved to the backup directory and that a new owncloud directory is created which lacks the data directory. ~~I have not checked if this scenario is true.~~

Again, not looking at the code in the script, I have tested this in another directory. The same result: the data directory content _is lost_ and the directory without content is forcefully recreated with `root:root` as `owner:group`(*).

It really does look like the existing `owncloud` directory is moved to the backup directory. Since the `owncloud/data` is not reinstated, it is empty. `data` is present in the backup directory.

The text output infers that the data directory could be missing (without fact-checking):
```
Creating or linking possible missing directories
mkdir /home/user/test/owncloud/data

mkdir /home/user/test/owncloud/apps-external
```
That could be improved by actual reporting what has happened.

So now I look at the script and there it is:
```
# check if upgrading an existing installation
if [ "$do_upgrade" = "y" ]; then
  read -p "Is the instance in maintenance mode? (y/N)? " -r -e answer
  (echo "$answer" | grep -iq "^y") && mmode="y" || mmode="n"
  if [ "$mmode" = "n" ]; then
    echo "Please enable maintenance mode first: sudo -u$htuser ./occ maintenance:mode --on"
    echo
    exit
  fi
  get_tar
  # rename the source for backup reasons
  if [ -d ${ocpath} ]; then
    mv $ocpath $oldocpath
  fi
fi
```
This is the line causing the removal of data from the `data` directory: 
`mv $ocpath $oldocpath`

The script does not display a warning or notice and it should. Additionally, it should ask for permission to restore the `data` directory as it was.

(*) The documentation does not explain which user should run the bash scripts. That should probably be added to the documentation too. I used `root`.

**Comment by mmattel** [comment]
> The data directory in the location being upgraded was factually deleted without warning

I can assure you that it is not deleted not even touched. But taking it from another perspective, it looks like that. What happens is, and you see this is in the code of the script, that there is a `mv` command. This command _renames_ the old instance name (eg. owncloud) to a new name (eg. owncloud-timestamp). This is because we do not do in-place upgrades which can cause issues with remnants. Therefore you have to either manually or automatically migrate relevant content from the renamed to the to the "new" location.
But what I have as takeaway is, that I will improve the documentation about this fact making it easier for readers to understand.

> Since the owncloud/data directory is not reinstated, it is empty. data is present in the backup directory

That observation is correct. When you do the non-linked upgrade, you manually have to migrate the data/ and apps-external/ directories. Migrating means either copy or move. This is up to the admin. As written above, data/ can be huge and therefore it depends on the admins choice to select a way best fitting to his environment. When you use linked directories, nothing gets migrated and the relevant directories stay in place, they only get relinked which is instant. Therefore this way is preferred and can be automated. Again, an admins decision which way is best for his environment.
In the same way as above, the takeaway is, that I will improve the documentation about this fact making it easier for readers to understand.

> Is the use of the word "adopt" intended?

This is a typo 🤦‍♂️ fixing asap

> From the script output: Please move/copy your data...

I will adapt the script to have that message at the beginning making it more clear in the order of steps to be done.

> data/ ... forcefully recreated with root:root

This is totally ok. The directory is empty and you migrate your existing data/ and apps-external/ to the new location which overwrites the existing ones with correct permissions. The script provides btw a possibility to set the proper rights and permissions on both directories if you have permission/ownership issues. This is not done automatically because such a task can take a while on a huge data/ directory, therefore it is selectable and an admins choice.
In the same way as above, the takeaway is, that I will improve the documentation about this fact making it easier for readers to understand.

Many thanks that you take the time which helps us to make the product better 😃

**Comment by mmattel** [comment]
I have updated the documentation and both sripts. Please take a look.
