### ISSUE TITLE
Transferring Files to Another User //Specification

### ISSUE THREAD

**Issue by dpapac** [owncloud/docs-server#449]
## Current Documentation
<details><summary>CLICK ME</summary>
<p>
You may transfer files from one user to another with occ. The command transfers either all or a limited set of files from one user to another. It also transfers the shares and metadata info associated with those files (shares, tags, and comments, etc). This is useful when you have to transfer a user’s files to another user before you delete them.
</p>
</details>

## New suggested Documentation
<details><summary>CLICK ME NEXT</summary>
<p>
You may transfer files from one user to another with occ. The command transfers either all or a limited set of files from one user to another. It also transfers the <b><i>outgoing</i></b> shares and metadata info associated with those files (shares, tags, and comments, etc). This is useful when you have to transfer a user’s files to another user before you delete them.
</p>
</details>

## WHERE Does This Need To Be Documented?
[Right here](
https://doc.owncloud.com/server/next/admin_manual/configuration/files/file_sharing_configuration.html#transferring-files-to-another-user)

## WHY Should This Change Be Made?

-to be more specific to our users
-conflicts with other documentations where we wrote it as in Source 1 or Source 2 
-[Source 1](https://doc.owncloud.com/server/next/admin_manual/configuration/server/occ_command.html#file-operations)
-[Source 2](https://doc.owncloud.com/server/next/admin_manual/configuration/server/occ_command.html#the-filestransfer-ownership-command)

**Comment by mmattel** [comment]
@dpapac thanks for raising this issue. Just for clarification, it is just about adding the word ˋoutgoingˋ - or?
