### ISSUE TITLE
[QA] new features in upcoming customgroups 0.7.0 

### ISSUE THREAD

**Issue by jnweiger** [owncloud/docs-server#578]
## WHAT Needs to be Documented?
* https://github.com/owncloud/customgroups/pull/521
* https://github.com/owncloud/customgroups/pull/522

## WHERE Does This Need To Be Documented (Link)?
?
https://github.com/owncloud/docs-server/blob/74e2c78c3f6d3c461cb405ddfb5a75c55a93f075/modules/developer_manual/pages/webdav_api/groups/custom_groups_endpoints.adoc
https://github.com/owncloud/docs-server/blob/327cfb321333291b507cefbcbe066df62dab00d3/modules/admin_manual/pages/configuration/user/user_management.adoc
...?

## WHY Should This Change Be Made?

maybe

## (Optional) What Type Of Content Change Is This? 
- [ ] New Content Addition
- [ ] Old Content Deprecation
- [ ] Existing Content Simplification
- [ ] Bug Fix to Existing Content

## (Optional) Which Manual Does This Relate To?
- [ ] Admin Manual
- [ ] Developer Manual
- [ ] User Manual
- [ ] Android
- [ ] iOS
- [ ] Branded Clients
- [ ] Desktop Client
- [ ] Other

**Comment by jnweiger** [comment]
customgroups 0.7.0 is released.

**Comment by mmattel** [comment]
Clsoing via #611
