### ISSUE TITLE
configreport application unknown to marketplace -> misleading 

### ISSUE THREAD

**Issue by dpapac** [owncloud/docs-server#579]
## WHAT Needs to be Documented?
When following along the '[Generate a Config Report](https://doc.owncloud.com/server/10.10/admin_manual/troubleshooting/providing_logs_and_config_files.html#generate-a-config-report)' documentation:

-> Suggests to download the app via the command line 
-> using the command:
```sudo -u www-data occ market:install configreport```   
->a misleading information is presented

## WHERE Does This Need To Be Documented (Link)?
[Here](https://doc.owncloud.com/server/10.10/admin_manual/troubleshooting/providing_logs_and_config_files.html#generate-a-config-report)

## WHY Should This Change Be Made?
The reason is that after this message is presented some customers don't proceed to check their Apps tab and just assume the marketplace can't provide the application even though it might already be installed and just needs to be enabled.

![misleading](https://user-images.githubusercontent.com/101094874/185582621-58745940-0b64-430f-bb26-54ecb14859a3.png)

## (Optional) What Type Of Content Change Is This? 
- [ ] New Content Addition
- [ ] Old Content Deprecation
- [ ] Existing Content Simplification
- [x] Bug Fix to Existing Content

## (Optional) Which Manual Does This Relate To?
- [x] Admin Manual
- [ ] Developer Manual
- [ ] User Manual
- [ ] Android
- [ ] iOS
- [ ] Branded Clients
- [ ] Desktop Client
- [ ] Other

**Comment by mmattel** [comment]
@dapac, thanks for catching 👍 
@jnweiger can you proof that the app `configreport` is always part of the shipment, because the ony app found on marketplace seaching for `config` is metrics. If it is part of the shipment, I will adapt texts accordingly.

**Comment by jnweiger** [comment]
Yes, configreport is a bundled app. It is part if the minimal and complete bundle.
`occ market:install configreport` does not make much sense.

To get the latest version of the app, **without** upgrading core, one would have to manually download from https://github.com/owncloud/configreport/releases and then use `occ market:install -l /abs/path/of/the/download/but/not/tmp/configreport-xxxx.tar.gz`
