### ISSUE TITLE
[QA] describe expectatins about expiry notifications

### ISSUE THREAD

**Issue by jnweiger** [owncloud/docs-server#592]
## WHAT Needs to be Documented?

When a share expires, activity notifications happen and mail is sent. We no longer expose the exact time of the expiry only the day
to the end user.

## WHY Should This Change Be Made?
Was overly specific, causing confusion. 
Suggestion see https://github.com/owncloud/enterprise/issues/5227#issuecomment-1231809084

## (Optional) What Type Of Content Change Is This? 
- [ ] New Content Addition
- [ ] Old Content Deprecation
- [ ] Existing Content Simplification
- [ ] Bug Fix to Existing Content

## (Optional) Which Manual Does This Relate To?
- [ ] Admin Manual
- [ ] Developer Manual
- [ ] User Manual
- [ ] Android
- [ ] iOS
- [ ] Branded Clients
- [ ] Desktop Client
- [ ] Other

**Comment by phil-davis** [comment]
> We no longer expose the exact time of the expiry only the day to the end user.

Correct - Note: the time was never "a thing" anyway. Shares expire at the end of the expiry date, not at "random" times throughout the day.
