### ISSUE TITLE
not sync

### ISSUE THREAD

**Issue by dannsatria** [owncloud/docs-server#610]
## (Optional) What Type Of Content Change Is This? 
- [ ] New Content Addition
- [ ] Old Content Deprecation
- [ ] Existing Content Simplification
- [ ] Bug Fix to Existing Content

## (Optional) Which Manual Does This Relate To?
- [ ] Admin Manual
- [ ] Developer Manual
- [ ] User Manual
- [ ] Android
- [ ] iOS
- [ ] Branded Clients
- [ ] Desktop Client
- [ ] Other

my files can't be updated in owncloud and other users who I'm share with it

**Comment by mmattel** [comment]
@dannsatria this is too less info to proceed. It seems you have issues with permissions. Have you followed the installation guide. Please also consult [our community forum](https://central.owncloud.org).

**Comment by mmattel** [comment]
Closing as there is no info provided
