### ISSUE TITLE
[QA] new app:config for impersonate

### ISSUE THREAD

**Issue by jnweiger** [owncloud/docs-server#633]
## WHAT Needs to be Documented?

New app:config variables for impersonate, with brekaing changes: group admins could always impersonate in the past, now this occ command is needed, before they can: `occ config:app:set impersonate impersonate_all_groupadmins --value true`

## WHERE Does This Need To Be Documented (Link)?

https://github.com/owncloud/docs-server/blob/master/modules/admin_manual/pages/configuration/general_topics/impersonate_users.adoc

## WHY Should This Change Be Made?

The current language in the section Allow Some or All Group Administrators to Impersonate Users
is somewhat muddy. 
- By default, when the Impersonate app is installed, ...
- When  the app is installed and configured ...
- When enabled and configured ...

Something can be configured with only install but not enabled?
Something else can be configured when also installed??

New confiuration as seen in https://github.com/owncloud/impersonate/pull/202#issue-1255080816

```
occ config:app:set impersonate enabled --value '["admin"]'
occ config:app:set impersonate impersonate_all_groupadmins --value true
```

## (Optional) What Type Of Content Change Is This? 
- [x] New Content Addition
- [ ] Old Content Deprecation
- [ ] Existing Content Simplification
- [x] Bug Fix to Existing Content

## (Optional) Which Manual Does This Relate To?
- [x] Admin Manual
- [ ] Developer Manual
- [ ] User Manual
- [ ] Android
- [ ] iOS
- [ ] Branded Clients
- [ ] Desktop Client
- [ ] Other

**Comment by mmattel** [comment]
Reopen, the referenced PR above is just a preperation as it belongs to all branches

**Comment by mmattel** [comment]
When the new app gets build, new screenshots need to be taken
