### ISSUE TITLE
[QA] Prominent Contacts and Calendar links are 404

### ISSUE THREAD

**Issue by jnweiger** [owncloud/docs-server#664]
Seen while testing ownCloud 10.11.0

![image](https://user-images.githubusercontent.com/1108546/193851870-70d18b78-2c03-427b-8afe-dc80bbbb0931.png)

The startup screen shows Calender and Contacts buttons. The links behind them are
* https://doc.owncloud.com/server/10.11/go.php?to=user-sync-calendars
* https://doc.owncloud.com/server/10.11/go.php?to=user-sync-contacts

Both result in 404 currently.

Expected behaviour:
* we maintain fixed entrypoints.

**Comment by mmattel** [comment]
@xoxys mind to have a look why resolving fails?
Just tested, it does not resolve for any of the last versions

**Comment by xoxys** [comment]
It resolves... Resolving and finding content on the resolved URL to deliver are two different things:

- `https://doc.owncloud.com/server/10.11/go.php?to=user-sync-calendars` resolves to `https://doc.owncloud.com/server/10.11/user_manual/pim/calendar.html#synchronizing-calendars-using-caldav` 
- `https://doc.owncloud.com/server/10.11/go.php?to=user-sync-contacts` resolves to `https://doc.owncloud.com/server/10.11/user_manual/pim/contacts.html#synchronizing-address-books`

I guess the file location and therefor the URL has changed in docs and nobody has set proper page aliases.

**Comment by mmattel** [comment]
After having a closer look...
Both `user-sync-calendars` and `user-sync-contacts` should now point to https://doc.owncloud.com/webui/next/classic_ui/pim/

When we restructured, only a view links needed special treatment. This is one of those very special cases where there is no replacement possible.

To resolve that issue, we have to fix that on the webserver...
@xoxys can you help

**Comment by cortho** [comment]
fyi: At least the Link I described at https://github.com/owncloud/core/issues/40405 is not working as expected again

**Comment by xoxys** [comment]
Link fixed via web server redirects now... but docs still have to manage changes to the content structure via page aliases. It's not intended to frequently change the web server config. If you think that's not possible in a particular case for whatever reason, please discuss this with us proactive next time.
