### ISSUE TITLE
extra "o" in "oowncloud-complete-latest.tar.bz2" on download page

### ISSUE THREAD

**Issue by mrjones-plip** [owncloud/docs-server#698]
## WHAT Needs to be Documented?
The correct number of `o`s in `owncloud`

## WHERE Does This Need To Be Documented (Link)?
[Download page](https://doc.owncloud.com/server/next/admin_manual/installation/manual_installation/manual_installation.html#download-owncloud)

## WHY Should This Change Be Made?
Because the `gpg` command fails when you spell it `oowncloud`:

> gpg --verify owncloud-complete-latest.tar.bz2.asc oowncloud-complete-latest.tar.bz2

## (Optional) What Type Of Content Change Is This? 
- [ ] New Content Addition
- [ ] Old Content Deprecation
- [ ] Existing Content Simplification
- [X] Bug Fix to Existing Content

## (Optional) Which Manual Does This Relate To?
- [X] Admin Manual
- [ ] Developer Manual
- [ ] User Manual
- [ ] Android
- [ ] iOS
- [ ] Branded Clients
- [ ] Desktop Client
- [ ] Other

**Comment by phil-davis** [comment]
@mrjones-plip thanks for reporting.

**Comment by mrjones-plip** [comment]
@phil-davis  - happy to help - nice job on the quick fix.

I tried to submit a PR myself, but failed b/c I was looking for `oowncloud` and [not](https://github.com/owncloud/docs-server/pull/699/files#diff-5ab1eced0c6a7a2a2cdc330c5a75b63b56c2dc6abeb585a7033688fd8f775f6aL97) `o{oc-complete-name}` :upside_down_face: 

Cheers!
