### ISSUE TITLE
Let's Encrypt with Apache2 currently has a slight error

### ISSUE THREAD

**Issue by jimadilo** [owncloud/docs-server#720]
## WHAT Needs to be Documented?

Configuration of Apache2 with Let's Encrypt

## WHERE Does This Need To Be Documented (Link)?

https://doc.owncloud.com/server/next/admin_manual/installation/letsencrypt/apache.html

## WHY Should This Change Be Made?

It is currently incorrect, and stops the config from working properly.

## (Optional) What Type Of Content Change Is This? 
- [ ] New Content Addition
- [ ] Old Content Deprecation
- [ ] Existing Content Simplification
- [x] Bug Fix to Existing Content

## (Optional) Which Manual Does This Relate To?
- [x] Admin Manual
- [ ] Developer Manual
- [ ] User Manual
- [ ] Android
- [ ] iOS
- [ ] Branded Clients
- [ ] Desktop Client
- [ ] Other

**Comment by mmattel** [comment]
Thanks for opening this issue. Mind to tell what is incorrect or makes the description not working?

**Comment by jimadilo** [comment]
Oh, sorry. Completely forgot.
It is currently:
`<VirtualHost *.80>`
Which does not match anything. It should be:
`<VirtualHost *:80>`

**Comment by mmattel** [comment]
Nice catch, thanks a lot 👍
