### ISSUE TITLE
oC Classic Deployment Recommendation: Missing Scenario 1,000 - 5,000 User 

### ISSUE THREAD

**Issue by dj4oC** [owncloud/docs-server#740]
## WHAT Needs to be Documented?
pot. oC EE client noticed that there is not sizing information between 1,000 - 5,000 users.

## WHERE Does This Need To Be Documented (Link)?
https://doc.owncloud.com/server/10.11/admin_manual/installation/deployment_recommendations.html

## WHY Should This Change Be Made?
This is and important range of pot. oC users

## (Optional) What Type Of Content Change Is This? 
- [X] New Content Addition

## (Optional) Which Manual Does This Relate To?
- [X] Admin Manual

**Comment by mmattel** [comment]
If you provide data for a recommendation, we can proceed adding that.
In such a case, docs can only add things that have been proven/tested by e.g. support.

**Comment by voroyam** [comment]
potential fix PR: https://github.com/owncloud/docs-server/pull/921

**Comment by mmattel** [comment]
Closing via #921
