### ISSUE TITLE
[QA] instance.sh has high potential of data loss when upgrading

### ISSUE THREAD

**Issue by jnweiger** [owncloud/docs-server#807]
Seen while testing the scripts presented in 
https://github.com/owncloud/docs-server/edit/10.11/modules/admin_manual/pages/installation/manual_installation/script_guided_install.adoc

Usecase: upgrade from oc10.9 to oc10.10
with standard data folder layout 
```
ls -la /var/www/owncloud/data
total 72
drwxrwx---  7 www-data www-data  4096 Jan 24 20:28 .
drwxr-xr-x 14 www-data www-data  4096 Jan 24 19:21 ..
-rw-rw-r--  1 www-data www-data   323 Jan 24 19:21 .htaccess
-rw-rw-r--  1 www-data www-data     0 Jan 24 19:21 .ocdata
drwxr-xr-x  6 www-data www-data  4096 Jan 24 19:38 admin
drwxrwxr-x  4 www-data www-data  4096 Jan 24 19:40 avatars
drwxr-xr-x  6 www-data www-data  4096 Jan 24 19:46 carol@lewis.com
drwxrwxr-x  2 www-data www-data  4096 Jan 24 19:25 files_external
-rw-r--r--  1 www-data www-data   145 Jan 24 20:28 htaccesstest.txt
-rw-rw-r--  1 www-data www-data     0 Jan 24 19:21 index.html
-rw-r-----  1 www-data www-data 29101 Jan 24 20:36 owncloud.log
```

* `sudo ./instance.sh`
  - Nicely asks several questions.
  - One question is unclear: link data directory yes or no. I chose link yes (the opposite of unlink ?) as I want to retain my existing /var/www/owncloud/data folder.
  - The script output ends with
```
...
owncloud/COPYING
owncloud/index.php
owncloud/CHANGELOG.md
owncloud/status.php

Creating or linking possible missing directories 
ln /var/www/owncloud/data --> /mnt/owncloud_data/data
ln /var/www/owncloud/apps-external --> /mnt/owncloud_data/apps-external

Copy existing *config.php and *.json files 

chmod files and directories excluding data and apps-external directory
chown files and directories excluding data and apps-external directory 
chown apps directory 
chown config directory 
chown updater directory 

chmod occ command to make it executable 

SUCCESS

Please change to your upgraded ownCloud directory: cd /var/www/owncloud
Please manually run: sudo -u www-data ./occ upgrade
Copy any changes manually added in .user.ini and .htaccess from the backup directory
Please manually run: sudo -u www-data ./occ maintenance:mode --off
Please manually remove the directory of the old instance: /var/www/owncloud_2023-01-24-20.35.44
When successfully done, re-run this script to secure your .htaccess files
```
The final instructions work fine, until the second last line.
I am instructed to delete /var/www/owncloud_2023-01-24-20.35.44
This is problematic, as 
a) /var/www/owncloud/data is now empty, and 
b) the original  data folder with all data of all users was sildently moved into /var/www/owncloud_2023-01-24-20.35.44
When I do the sequence of instructions as suggested, all data is lost.

(Yes, I am stupid. Every half sane admin should check folder contents before removing anything. But that hint is not there)

**Comment by mmattel** [comment]
I recommend reading [General Info](https://doc.owncloud.com/server/10.11/admin_manual/installation/manual_installation/script_guided_install.html#general-info) with the topics 
* **Installation** and 
* **Migrating from standard to linked directories**

Clearly described...
