### ISSUE TITLE
[QA] instance.sh suggests to run occ upgrade while still in maintenance mode

### ISSUE THREAD

**Issue by jnweiger** [owncloud/docs-server#809]
Seen while testing the scripts presented in 
https://github.com/owncloud/docs-server/edit/10.11/modules/admin_manual/pages/installation/manual_installation/script_guided_install.adoc

Usecase: upgrade from oc10.11 to master

After the script is run, amongst others, this sequence of actions is suggested:
```
Please manually run: sudo -u www-data ./occ upgrade
Copy any changes manually added in .user.ini and .htaccess from the backup directory
Please manually run: sudo -u www-data ./occ maintenance:mode --off
```

As instance.sh initially asked us to put the server in maintenance mode, the occ upgrade command will be attempted in maintenance mode, and this fails:

```
sudo -u www-data ./occ upgrade
ownCloud is in maintenance mode - no app have been loaded

<warning>ownCloud is in maintenance mode</warning>
Maybe an upgrade is already in process. Please check the logfile (data/owncloud.log). If you want to re-run the upgrade procedure, remove the "maintenance mode" from config.php and call this script again.
```

Expected behavior:
* a sequence of commands that agrees with occ usage.
* first maintenance mode off, then upgrade.

**Comment by mmattel** [comment]
Thanks for catching, fix is on the way
