### ISSUE TITLE
[QA] docs claim that search_elastic works with encryption

### ISSUE THREAD

**Issue by jnweiger** [owncloud/docs-server#864]
## WHAT Needs to be Documented?
According to our tests today, it does not work.
According to @hodyroff it should not work.

## WHERE Does This Need To Be Documented (Link)?
https://doc.owncloud.com/server/next/admin_manual/configuration/general_topics/search.html#known-limitations

## WHY Should This Change Be Made?
This is wrong:
```
Known Limitations

Currently, the app has the following known limitations:
...
    When using encryption, the app only works with the default Master Key encryption module.
```

Correct is:
 - "When using encryption, the app does not work."
 - Neither Master Key encryption encryption nor User Key encryption work.
 - We don't support anything else than Master Key encryption, we should not hint that there is a even a choice.

## (Optional) What Type Of Content Change Is This? 
- [ ] New Content Addition
- [ ] Old Content Deprecation
- [ ] Existing Content Simplification
- [x] Bug Fix to Existing Content

## (Optional) Which Manual Does This Relate To?
- [x] Admin Manual
- [ ] Developer Manual
- [ ] User Manual
- [ ] Android
- [ ] iOS
- [ ] Branded Clients
- [ ] Desktop Client
- [ ] Other

**Comment by jnweiger** [comment]
It may seem, that search elastic works "when encryption is enabled". But this is an illusion:
* When encryption is enabled, existing files can remain unencrypted. Unless touched, or occ encrypt all is executed.
* Files that remain unencrypted are happily indexed by search-elastic. 

*If* search_elastic would actually work with encrypted files, we should document the security implications with regards to the index data, which is stored unencrypted in the elastic server.

**Comment by mmattel** [comment]
Closing via #866
