### ISSUE TITLE
modules/developer_manual/pages/testing/ui-testing.adoc still mentions mailhog

### ISSUE THREAD

**Issue by jnweiger** [owncloud/docs-server#924]
## WHAT Needs to be Documented?
mailhog is no longer used for testing, we now use inbucket.

## WHERE Does This Need To Be Documented (Link)?
modules/developer_manual/pages/testing/ui-testing.adoc

## WHY Should This Change Be Made?
Acceptance tests cannot succeed, when the setup is done according to the  documentation:
```
   ...
    And the administrator clicks on send test email in the admin general settings page using the webUI # WebUIAdminGeneralSettingsContext::theAdministratorClicksOnSendTestEmailInTheAdminGeneralSettingsPageUsingTheWebui()
    Then the email address "admin@owncloud.com" should have received an email with the body containing # EmailContext::emailAddressShouldHaveReceivedAnEmailWithBodyContaining()
      """
      If you received this email, the settings seem to be correct.
      """
      cURL error 7: Failed to connect to 127.0.0.1 port 9000: Connection refused
```

Docu does not mention port 9000.
Instead we say ```docker run -p 1025:1025 -p 8025:8025 mailhog/mailhog``` 
Cannot work. Different ports, and possibly also different protocol.

## (Optional) What Type Of Content Change Is This? 
- [ ] New Content Addition
- [ ] Old Content Deprecation
- [ ] Existing Content Simplification
- [x] Bug Fix to Existing Content

## (Optional) Which Manual Does This Relate To?
- [ ] Admin Manual
- [x] Developer Manual
- [ ] User Manual
- [ ] Android
- [ ] iOS
- [ ] Branded Clients
- [ ] Desktop Client
- [ ] Other

**Comment by phil-davis** [comment]
Note for reference: the change to core tests happened in core PR https://github.com/owncloud/core/pull/40442

**Comment by mmattel** [comment]
If this goes into 10.12.1 we need to backport the fix also

**Comment by jnweiger** [comment]
Needed for 10.12 but not for 10.11  - the change happened one month after 10.11 was released.
