### ISSUE TITLE
Document kerberos support for WND

### ISSUE THREAD

**Issue by jvillafanez** [owncloud/docs-server#937]
## WHAT Needs to be Documented?

New added kerberos support for WND. Expected to be released with WND 2.2.0
I think the expected setup and requirements are in https://github.com/owncloud/windows_network_drive/pull/423#issuecomment-1453240078

## WHERE Does This Need To Be Documented (Link)?

Related to the windows_network_drive app.

## WHY Should This Change Be Made?

Kerberos support requires additional changes in the config.php file in order to work, so those needs to be documented. In addition, the requirements might not be suitable for all the environments.

## (Optional) What Type Of Content Change Is This? 
- [x] New Content Addition
- [ ] Old Content Deprecation
- [ ] Existing Content Simplification
- [ ] Bug Fix to Existing Content

## (Optional) Which Manual Does This Relate To?
- [x] Admin Manual
- [ ] Developer Manual
- [ ] User Manual
- [ ] Android
- [ ] iOS
- [ ] Branded Clients
- [ ] Desktop Client
- [ ] Other

@mmattel feel free to ping me if you need more info.

**Comment by mmattel** [comment]
Note that we do not have atm a documentation about the kerberos app...

@jnweiger what is the status of the kerberos app with regards to docs?

**Comment by jvillafanez** [comment]
While it's a good idea to link it with the kerberos app, this is intended to be independent between each-other. WND doesn't need to the kerberos app to use the kerberos support.

**Comment by jnweiger** [comment]
@GeraldLeikam tries to figure it out. The only pieces of documentation seem to be what  @jvillafanez wrote in the wnd tickets.
