### ISSUE TITLE
[OIDC] Document scope and prompt parameters in vanilla desktop + mobile apps

### ISSUE THREAD

**Issue by michaelstingl** [owncloud/docs-server#938]
## WHAT Needs to be Documented?

Vanilla desktop + mobile apps send fixed scope and prompt parameters in the OIDC login flow. (changing them via branding and MDM should be documented somewhere else: https://github.com/owncloud/docs-server/issues/384 )

## WHERE Does This Need To Be Documented (Link)?

- https://doc.owncloud.com/server/admin_manual/configuration/user/oidc/oidc.html
(new paragraph, after "Client IDs, Secrets and Redirect URIs") 

## WHY Should This Change Be Made?

Admins and support team should know about this.

## (Optional) What Type Of Content Change Is This? 
- [x] New Content Addition
- [ ] Old Content Deprecation
- [ ] Existing Content Simplification
- [ ] Bug Fix to Existing Content

## (Optional) Which Manual Does This Relate To?
- [x] Admin Manual
- [ ] Developer Manual
- [ ] User Manual
- [ ] Android
- [ ] iOS
- [ ] Branded Clients
- [ ] Desktop Client
- [ ] Other

**Comment by TheOneRing** [comment]
https://github.com/owncloud/client/blob/9aa319f4852f1065be1809d2a1c2231ed1d2062b/src/libsync/theme.cpp#L619-L627

**Comment by jesmrec** [comment]
Android app:

3.x versions (3.0.4 as stable):

- scope is `openid offline_access email profile` by default (brandable)
- prompt not used

4.0+ versions (incoming)

- scope is `openid offline_access email profile` (brandable)
- prompt is `select_account` by default. It will be brandable via https://github.com/owncloud/ownbrander/issues/1062

**Comment by felix-schwarz** [comment]
The iOS app sends:
- for `scope`: `openid offline_access email profile` (brandable via `authentication-oauth2.oidc-scope`)
- for `prompt`: `select_account consent` (not currently brandable, but will take care it is via `authentication-oauth2.oidc-prompt` in version 12.0)

**Comment by michaelstingl** [comment]
### ocis.ocis-traefik.latest.owncloud.works



![4A0F29E3-B130-499A-BF7A-FB07D859A221_1_102_o](https://user-images.githubusercontent.com/214010/232057954-077d6f9d-2850-4daa-b15b-73ae79d10ee5.jpeg) | ![6958037C-760D-410C-871B-66D5A50A1328_1_102_o](https://user-images.githubusercontent.com/214010/232058003-e2e12e15-52bd-4f84-8cc2-c68c203779cd.jpeg)
-- | --
`prompt`: `select_account` | `prompt`: `consent`

### ocis.ocis-keycloak.latest.owncloud.works

Keycloak doesn't respect the `prompt`: `select_account`:

![E0F19F83-7603-4804-B5F1-4A8E69376A17_1_102_o](https://user-images.githubusercontent.com/214010/232059515-be7d9213-6c35-4d06-bd8f-924b949449f6.jpeg)

It opens directly the `prompt`: `consent` in the context of the existing user session. @wkloucek any idea?
