### ISSUE TITLE
[QA] Manual copy / paste misses redirects

### ISSUE THREAD

**Issue by jnweiger** [owncloud/docs-server#94]
Seen in https://doc.owncloud.com/server/next/admin_manual/installation/quick_guides/ubuntu_20_04.html#set-up-a-cron-job

User tries to highlight the code with the mouse, Everything except the `>` character can be highlighted.

![image](https://user-images.githubusercontent.com/1108546/154660569-9aa9409e-2796-4563-bd9a-0010b36c36f6.png)

When the result is pasted, the command fails with an error message of 
```
bash: /var/spool/cron/crontabs/www-data: Permission denied
```

Something is rotten in the state of Antora.

Backports needed.

FYI: @emma1382 this is what happened to you :-)

**Comment by jnweiger** [comment]
The next code snippet further down on the page (user:sync) uses a very long line..
This is more challenging due to horizontal scrolling, but works correctly either way.

**Comment by mmattel** [comment]
> Something is rotten in the state of Antora.

Come on, calm down, I have (possibly) identified what it is. Needs some more investigation (around highlight.js) and a change in docs-ui.

> Use the "invisible" clipboard icon on the right hand side...

Yes, the size, the location and other stuff could be improved

> code snippet for ldap user:sync ...

Thanks for highlighting the issue. Need to look at this

**Comment by jnweiger** [comment]
> Yes, the size, the location and other stuff could be improved

Size and location is just fine. The "other stuff" is what bothers me most: invisibility. Modern UX design ideas ("never distract the user with useful information") gets in our way here.
