### ISSUE TITLE
New config.php option `wnd2.cachewrapper.normalize` 

### ISSUE THREAD

**Issue by jnweiger** [owncloud/docs-server#953]
## WHAT Needs to be Documented?
https://github.com/owncloud/windows_network_drive/pull/430 introduced a new option to make working with UTF-8 filenames more robust.
To enable this new behaviour, a config.php option `wnd2.cachewrapper.normalize` was introduced, it defaults to false.
## WHY Should This Change Be Made?
The issue is complicated to describe. Technically, there are UTF-8 glyphs, that have two 100% legel represenations in UTF-8 space. A filename that contains such a glyph, may be written with two different byte sequences in the filesystem. The two variants are known as NFD ad NFC form. ownCloud usually normalizes names to NFC, but WND shares living on a MacOS HFS+ Filesystems have to normalize names to NFD, as required by that filesystem.
The code now probes both forms and uses the one that exists in the filesystem. 

## (Optional) What Type Of Content Change Is This? 
- [ ] New Content Addition
- [ ] Old Content Deprecation
- [ ] Existing Content Simplification
- [ ] Bug Fix to Existing Content

## (Optional) Which Manual Does This Relate To?
- [ ] Admin Manual
- [ ] Developer Manual
- [ ] User Manual
- [ ] Android
- [ ] iOS
- [ ] Branded Clients
- [ ] Desktop Client
- [ ] Other

**Comment by mmattel** [comment]
master and 10.12?

**Comment by jnweiger** [comment]
All backports, please. This is released in the wnd app, and it is compatible with all core version.

**Comment by jnweiger** [comment]
There is also an NFD setting per mount. Not sure how the interaction between this per mount setting and the global normalize variable is. :see_no_evil: 

![grafik](https://user-images.githubusercontent.com/1108546/234140545-49cd219c-3704-4814-8abd-71b9c5ac4a49.png)

**Comment by jnweiger** [comment]
The UI checkbox '[ ] Compatibility with Mac NFD encoding (slow)' is there, with and without `wnd2.cachewrapper.normalize` set. 

I'd assume, 
* With only the UI checkbox enabled, it does not really work? It only works, when the variable is also set?

**Comment by pako81** [comment]
Yes, this is what I meant. The UI checkbox is not new, but the new config.php option should correctly work only when the checkbox is enabled.

**Comment by jnweiger** [comment]
The README says `otherwise there could be problems` -- not really helpful :see_no_evil: 
In any case, I could not find any misbehaviour, errors or crashes, when one is set and the other is not.

**Comment by pako81** [comment]
maybe we should double-check with @jvillafanez if this is or not an hard requirement.

**Comment by jvillafanez** [comment]
For collaborative mode you'll need both. It's a hard requirement. It's either both (if you need NFD) or none (if you don't).

The checkbox in the mount point configuration is controlled by core and no information about it is transferred to the wnd app in any way, so basically, the app won't know whether the checkbox is marked or not.
The wnd collaborative mode has to check the permissions of the files each time someone access to the filecache. The filecache contains the filenames normalized to NFC, so the wnd app will try to check the permissions using that filename. If the file in windows contains NFD chars, windows won't find the file and the app will consider the user doesn't have access to the file, so the file won't appear.

I expect that, if any `wnd2.cachewrapper.normalize` option isn't set and it's required, files containing NFD chars won't appear even if the NFD checkbox is marked in the mount point configuration. This is what has been happening in previous versions. It might be harmless if there is no file with NFD chars.
