### ISSUE TITLE
Persistent versions feature laking explanation

### ISSUE THREAD

**Issue by voroyam** [owncloud/docs-server#979]
## WHAT Needs to be Documented?
how to enable to see the author of a version

## WHERE Does This Need To Be Documented (Link)?
https://doc.owncloud.com/server/next/admin_manual/configuration/files/file_versioning.html#show-the-author-of-a-version

## WHY Should This Change Be Made?
because the docs does not tell you how to enable it, it just tells you that you can. No screenshot, no description, nothing.

**Comment by mmattel** [comment]
Honestly speaking, I also have no clue how this works. Any info is welcomed.

**Comment by voroyam** [comment]
> Honestly speaking, I also have no clue how this works. Any info is welcomed.

in communications with @mrow4a 

maybe he can explain here.
